### ISSUE TITLE
Release at conda-forge

### ISSUE THREAD

**Issue by lresende** [jupyter-incubator/enterprise_gateway#153]
https://github.com/conda-forge/staged-recipes

**Comment by liukun1016** [comment]
Here is the PR created for this issue on the conda-forge side:
https://github.com/conda-forge/staged-recipes/pull/4376

**Comment by liukun1016** [comment]
The conda recipe for kernel gateway as a reference:
https://github.com/conda-forge/jupyter_kernel_gateway-feedstock/blob/master/recipe/meta.yaml

**Comment by liukun1016** [comment]
The PR passed all the test cases.

But we need to first upload our 0.7.0 tar file to Pypi before we release the 0.7.0 version on Conda, since the PR would need to download the tar file with the corresponding version before build it.

**Comment by liukun1016** [comment]
Need to add `pexpect` as a required lib inside the `requirements-conda.txt` since it is not in the conda side.

Here is the link to the build where the `pexpect` lib was not listed as one of the `requirements` in `meta.yaml` and thus an error of `ImportError`:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18805/job/8jcd6gm8hhkcw6e3#L551


Going to open a PR for this, and as long as it is merged, we can close this issue.

**Comment by liukun1016** [comment]
The PR was merged and we could now use `conda install jupyter_enterprise_gateway` to install our 0.7 version. So now close this issue.
