### ISSUE TITLE
[Q] How can enterprise_gateway be used in conjunction with Jupyter dashboards?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/enterprise_gateway#186]
At the moment [kernel_gateway](https://github.com/jupyter/kernel_gateway) is [well-supported](https://github.com/rs2/pydata-2017-jupyter-workshop/blob/master/docker/Dockerfile.nb#L38) by [Jupyter dashboards](https://github.com/jupyter/dashboards) as well as Jupyter notebooks (when using [nb2kg](https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg) extension for notebooks).

How could enterprise_gateway be used to substitute kernel_gateway for both Jupyter notebooks as well as dashboards? There's no mention of these in the [roadmap](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/roadmap.html).

**Comment by kevin-bates** [comment]
Hello @rs2, thanks for the question.
One of our primary tenets for Enterprise Gateway was that it be completely compatible with Kernel Gateway.  As such, it is built directly on top of JKG so you should be able to literally change the command target from kernelgateway to enterprisegateway.  In fact, we use the same unit tests that are found in JKG - just to preserve that compatibility.  

Although we haven't spent time using dashboards, our primary vehicle for accessing Enterprise Gateway is NB2KG, which requires no changes.  So I guess you could say this doesn't appear in our roadmap because its a road already traveled. :-)
