### ISSUE TITLE
Update PYTHONPATH in kernel.json to be able to import locally installed modules 

### ISSUE THREAD

**Issue by sanjay-saxena** [jupyter-incubator/enterprise_gateway#193]
To be able to successfully `import` modules that are installed using `!pip install --user <module_name>` from within a notebook cell, `PYTHONPATH` defined in `kernel.json` must be augmented to include the following path:

```
${HOME}/.local/lib/python-2.7/site-packages
```

This change should be made to the `kernel.json` files defined for both `YARN Client Mode`(aka `Distributed Proxy Mode`) and `YARN Cluster Mode`.

**Comment by sanjay-saxena** [comment]
@kevin-bates -- Who owns `/opt/anaconda2/share/jupyter/kernels/kernel.json`? Was it populated/created by JKG?

**Comment by kevin-bates** [comment]
Its "brought into existence" by virtue of installing the ipython kernel - which comes, in this environment, as the result of installing anaconda.  I'm not entirely sure where it lives in github.  Modifications like you're suggesting are the responsibility of the entity producing the end result product and not necessarily the provider.  

JKG does not deliver any kernelspecs and the kernelspecs we deliver are for example purposes.  All envs will likely need modifications here and there to what we provide.  That said, I agree that our _example_ python kernelspecs should include the `${HOME}` segment entry since we're actually introducing multi-user _sensitivity_.

**Comment by sanjay-saxena** [comment]
This was fixed by PR #194.
