### ISSUE TITLE
Use separate log file for each remote kernel launch

### ISSUE THREAD

**Issue by lresende** [jupyter-incubator/enterprise_gateway#221]
- Use enterprise_gateway prefix instead of jeg
- Identify if we could add kernel_id or something that help correlate the log to running sessions/kernels

**Comment by kevin-bates** [comment]
How about this format - probably don't need `enterprise_gateway` or `jeg` since its now kernel-specific...
We should introduce a different env variable rather than `EG_PROXY_LAUNCH_LOG` - which pointed to a single filename.  Instead, it should be directory-based and perhaps more generic, say, `EG_LOG_DIR` and its default should be `/var/log`.
When remote (client mode) kernels are launched, their output will redirect to `${EG_LOG_DIR}/kernel-<kernel-id>-launch.log`

**Comment by sanjay-saxena** [comment]
I am not sure if there are multiple threads involved. If there are, then it would be good to have the thread-id/thread-name in the `ConversionPattern` equivalent of log4j like mechanism.

**Comment by kevin-bates** [comment]
@sanjay-saxena - formatting is an entirely different issue and a function of what each launcher - and its embedded kernel - log.  As a result, I've updated the name of this issue to be more specific.  Since there's less control over what the launchers and kernels log, and it implies the introduction of 'loggers' in those components (well, or some strict convention), its probably best we first place the kernel/launcher outputs into separate files.

Currently, most of these entries don't even have timestamps, let alone thread ids.   Here's an example - which includes output from the run.sh script, launcher, and kernel...
```
Starting IPython kernel for Spark 2.1 in Yarn Client mode as user Foo

+ eval exec /usr/hdp/current/spark2-client/bin/spark-submit '--master yarn --deploy-mode client --name 7893e8c0-882b-4d32-95ab-aa7cb44a790c' /usr/local/share/jupyter/kernels/spark_2.1_python_yarn_client/scripts/launch_ipykernel.py '' /home/elyra/.local/share/jupyter/runtime/kernel-7893e8c0-882b-4d32-95ab-aa7cb44a790c.json --RemoteProcessProxy.response-address 172.16.187.100:50606
++ exec /usr/hdp/current/spark2-client/bin/spark-submit --master yarn --deploy-mode client --name 7893e8c0-882b-4d32-95ab-aa7cb44a790c /usr/local/share/jupyter/kernels/spark_2.1_python_yarn_client/scripts/launch_ipykernel.py /home/elyra/.local/share/jupyter/runtime/kernel-7893e8c0-882b-4d32-95ab-aa7cb44a790c.json --RemoteProcessProxy.response-address 172.16.187.100:50606
Using connection file '/tmp/kernel-7893e8c0-882b-4d32-95ab-aa7cb44a790c_dmT5fD.json' instead of '/home/elyra/.local/share/jupyter/runtime/kernel-7893e8c0-882b-4d32-95ab-aa7cb44a790c.json'
Signal socket bound to host: 0.0.0.0, port: 59589
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /tmp/kernel-7893e8c0-882b-4d32-95ab-aa7cb44a790c_dmT5fD.json
17/11/10 10:06:54 INFO SparkContext: Running Spark version 2.1.1.2.6.1.0-129
17/11/10 10:06:55 INFO SecurityManager: Changing view acls to: elyra
```
