### ISSUE TITLE
Create user impersonation integration tests

### ISSUE THREAD

**Issue by lresende** [jupyter-incubator/enterprise_gateway#238]
Enable user impersonation via EG_IMPERONSATION_ENABLED and make sure !whoami result is same as KERNEL_USERNAME

**Comment by liukun1016** [comment]
Currently I have two ideas about the implementation of this issue:

1. add a `!whoami` code cell on one of the python notebooks (client and/or cluster mode), and use a flag argument that when it is specified as e.g. `bob` instead of `None`, compare the result from the `whoami` cell with `bob`

So this way requires changes on both notebook side (just one more code cell) and some logic on the itest src codes (e.g. another argument like `impersonation_username`)

2. add a function to compare the flag argument username when it is specified, by sending a code message `whoami` to a python kernel by socket. 

So this way requires more changes on the src codes side
