### ISSUE TITLE
Multiple spark-yarn kernels

### ISSUE THREAD

**Issue by kkalugerov** [jupyter-incubator/enterprise_gateway#361]
Can we have multiple spark-yarn kernels for example I have one fully running spark-python-yarn-cluster kernel and when I create a new one  spark-python-yarn-client kernel and try to invoke it in jupyter notebook the enterprise gateway gives me HTTP 403 ERROR ( FORBIDDEN ) :

https://www.dropbox.com/s/mgx2oetunfe5mhs/Screenshot%20from%202018-05-28%2010-05-23.png?dl=0
https://www.dropbox.com/s/q6yodwzk8i787et/kernel-error.txt?dl=0

But if I run some other kernel like spark-python-yarn-cluster  there is no problem... The problem comes only when I try to start the mentioned kernel.

**Comment by kevin-bates** [comment]
If you're running with the `DistributedProcessProxy` - which our default YARN client kernelspecs do - then you need to ensure that SSH is properly configured between the nodes of your cluster.  If you haven't setup the Remote Hosts, the its using localhost as the default (but still running in loopback).

YARN cluster mode doesn't require SSH so that's why you don't see this issue with those kernelspecs.

The [Troubleshooting page](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/troubleshooting.html) makes mention of this issue.

Adding @lresende since he's more knowledgable on the SSH configuration front than myself.

**Comment by kkalugerov** [comment]
Fix it ! Thanks !

**Comment by kevin-bates** [comment]
@kkalugerov - glad to hear that.  Closing issue.
