### ISSUE TITLE
Support for PBS / TORQUE HPCs?

### ISSUE THREAD

**Issue by bashterm** [jupyter-incubator/enterprise_gateway#401]
I was wondering if there are plans currently, and if not how hard it would be to do myself, to add support for HPCs running PBS based schedulers.

**Comment by kevin-bates** [comment]
Hello @bashterm - thank you for the issue.

Torque HPC/PBS is not something on our immediate roadmap, but I suspect you should be able to write a [Process Proxy](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/system-architecture.html#process-proxy) and configure a [Remote Kernel Spec](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/system-architecture.html#remote-kernel-spec) to meet your needs.  We'd love the contribution and would gladly assist in helping that along.

I don't know anything about OpenPBS, but if there's a REST API for interacting with the resource manager, the process proxy would likely resemble the [YarnClusterProcessProxy](https://github.com/jupyter-incubator/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/yarn.py) or [ConductorClusterProcessProxy](https://github.com/jupyter-incubator/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/conductor.py) implementations we do have.

One thing I notice is that this environment appears to be more batch based.  Would the idea be to submit an entire notebook (of cells) to this environment such that the human interactivity is eliminated?  I.e., use an actual notebook to iterate/experiment with a model, then submit that "batch" to this system as a whole?

**Comment by bashterm** [comment]
I've checked, and there's no REST API. However, it looks like I can get software running on the head node so I could possibly build my own.

Unfortunately that's out of scope for my current project, but it's something I'll add to my list.

**Comment by kevin-bates** [comment]
@bashterm - thank you for checking on that.  

When you get around to building a process proxy, please check back in.  I will be happy to assist however I can.

As a general consideration, you'll really just need a way to "name the job" and then manage its life cycle - a REST API is not required.  Once launched (which is typically a function of the kernelspec argv stanza), EG would then need a means of identifying the job.  In all cases so far, we use the kernel_id as part of the job identity, since that's the primary piece EG has.

Lifecycle management operations consist of the ability to determine the job is still active (used by the jupyter framework polling mechanism) and termination (used by the jupyter framework to shutdown the kernel).

Signaling for interrupt support is also something that may be necessary, but that should be handled as a function of the kernel _launcher_ that embeds the target kernel - so that's probably not a resource provider issue.

At any rate, please check back in when you have a chance to take a closer look.  I'm going to go ahead and close this issue.
