### ISSUE TITLE
bug for kubernetes-kernel-tf-py-gpu

### ISSUE THREAD

**Issue by SolarisYan** [jupyter-incubator/enterprise_gateway#425]
Hi there,
i find the image for tf-gpu in docker hub is elyra/kubernetes-kernel-tf-py-gpu:dev, but the kernel.json is ["image_name": "elyra/kubernetes-kernel-tf-py-gpu:dev"]( https://github.com/jupyter-incubator/enterprise_gateway/blob/7ce03b2bea9ad201903c327984f197e8be1a1d7c/etc/kernelspecs/python_tf_gpu_kubernetes/kernel.json#L7), so it can't start the kernel pod in k8s.

Another issue, i use the images elyra/kubernetes-enterprise-gateway:dev to start the gateway, and select the Python on Kubernetes with Tensorflow with GPUs, it can't start it and i found that there'is no /usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py and kernel-pod.yaml files, so it failed.

**Comment by kevin-bates** [comment]
@SolarisYan - thank you for the issue.  Yes, you are correct.  I had renamed the image but failed to update the `kernel.json`.  (I believe your first image reference above should be _elyra/kubernetes-kernel-tf-**gpu-py**:dev_ - see how easy it is to make that mistake :smile: ). A PR to fix this would be apprecianted.  In the meantime, you should be able to manually update the kernel.json file if you've mounted the kernelspes via a PersistentVolume (we provide an example for this commented out in the `enterprise-gateway.yaml` file) or you can rebuild the `kubernetes-enterprise-gateway` image.

The reason you don't see the supporting files is because you are not using the kernelspecs tar file that is part of the "distribution", which massages the appropriate kernelspec directories with appropriate files.  To build the kernelspecs tar file, issue `make kernelspecs`.

Please note that kubernetes support is still under development.  We hope to include this in our 2.0 release in Q4 - time permitting.

Also please note that the kernelspec files we provide should be considered `examples` and will likely require modifications to fit your environment.

I hope that helps.

**Comment by kevin-bates** [comment]
@SolarisYan - I pushed an updated [`elyra/kubernetes-enterprise-gateway:dev`](https://hub.docker.com/r/elyra/kubernetes-enterprise-gateway/) image containing the fix.  That said, since you'll need to customize the `kernel-pod.yaml` for the tf-gpu image, you'll likely need to mount `/usr/local/share/jupyter/kernels` in a PV and load the tar file.  For that, take a look at the commented out PV portions of [`enterprise-gateway.yaml`](https://github.com/jupyter-incubator/enterprise_gateway/blob/master/etc/kubernetes/enterprise-gateway.yaml).

**Comment by SolarisYan** [comment]
@kevin-bates Yes, i have do that for my work, thank you for your prompt reply
